services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    restart: always
    env_file: .env
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    networks:
      inception:

  wordpress:
    build: requirements/wordpress/.
    expose:
      - "9000"
    container_name: wp-php
    restart: always
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    networks:
      inception:

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      inception:

networks:
  inception:

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ahuge/data/wordpress
      o: bind

  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ahuge/data/mariadb
      o: bind
